### ISSUE TITLE
如何使用自己的训练模型

### ISSUE THREAD

**Issue by chiawenwang** [qq44642754a/Yolov5_ros#1]
请问，自己的训练模型为什么是放在model下呢？还是说是放在weights下？.pt文件是yolov5训练得到的格式吗？还是需要自己编写呢？谢谢！

**Comment by qq44642754a** [comment]
你好，训练好的模型，你只需要把训练好的权重文件（就是.pt 的文件）放到weights 文件夹下即可。然后记得要修改launch文件中weights的路径（修改下名称即可）。

**Comment by chiawenwang** [comment]
好的，谢谢解答！
