### ISSUE TITLE
请问您使用的什么相机？

### ISSUE THREAD

**Issue by Lixinixn115** [qq44642754a/Yolov5_ros#2]
博主您好！
请问您使用的什么相机？
您用的yolov5是哪个版本？
我是载TX2上安装了torch1.8,python是3.6.9，在运行roslauch那步报错ImportError: No module named torc但是运行别的程序可以调用torch
希望得到博主的回复，谢谢博主！

**Comment by qq44642754a** [comment]
> 博主您好！ 请问您使用的什么相机？ 您用的yolov5是哪个版本？ 我是载TX2上安装了torch1.8,python是3.6.9，在运行roslauch那步报错ImportError: No module named torc但是运行别的程序可以调用torch 希望得到博主的回复，谢谢博主！

进入到配置好的conda环境中去执行launch文件

**Comment by Lixinixn115** [comment]
> 

作者能否加个联系方式，我的QQ：1481932986，非必要绝对不打扰，感谢。
