### ISSUE TITLE
请问没有GPU，纯CPU可以跑您的代码吗？

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [qq44642754a/Yolov5_ros#4]

**Comment by ZOUJIASHUAI** [comment]
UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
^C[yolov5_ros-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by qq44642754a** [comment]
可以的，把launch 文件里的use_cpu这个[param](https://github.com/qq44642754a/Yolov5_ros/blob/master/yolov5_ros/yolov5_ros/launch/yolo_v5.launch)的值改为true
